import type { ChatInviteLink, ChatInviteLinkMember, TelegramClient } from '@mtcute/node'
import type * as W from './group-write-types.js'
import { normalizePeerId, requireGroup, throwWriteError } from './mtcute-group-helpers.js'

export class MtcuteGroupInvites {
  constructor(private readonly client: TelegramClient, private readonly ensureReady: () => Promise<void>) {}
  private async group(chat: W.GroupPeer) { await this.ensureReady(); const id = normalizePeerId(chat); try { return { id, group: requireGroup(await this.client.getChat(id), chat) } } catch (e) { throwWriteError(e, chat) } }
  private invite(i: ChatInviteLink): W.TelegramGroupInviteRecord { const raw = i.raw as typeof i.raw & { title?: string }; return { link: i.link, title: raw.title ?? null, creator_id: i.creator?.id ?? null, created_at: i.date?.toISOString() ?? null, expires_at: i.endDate?.toISOString() ?? null, usage_limit: Number.isFinite(i.usageLimit) ? i.usageLimit : null, usage_count: i.usage, request_needed: i.approvalNeeded, revoked: i.isRevoked } }
  private async mutate<K extends W.TelegramGroupMutationOperation>(r: { chat: W.GroupPeer }, operation: K, fn: (id: string | number) => Promise<void>): Promise<W.TelegramGroupWriteResult<K>> { const x = await this.group(r.chat); try { await fn(x.id); return { operation, chat_id: x.group.id } } catch (e) { throwWriteError(e, r.chat) } }
  async listInvites(r: W.TelegramListInvitesRequest) { const x = await this.group(r.chat); try { const rows = await this.client.getInviteLinks(x.id, { limit: r.limit }); return { chat_id: x.group.id, invites: rows.map(i => this.invite(i)), total: validTotal(rows.total) } } catch (e) { throwWriteError(e, r.chat) } }
  async getInvite(r: W.TelegramGetInviteRequest) { const x = await this.group(r.chat); try { return { chat_id: x.group.id, invite: this.invite(await this.client.getInviteLink(x.id, r.link)) } } catch (e) { throwWriteError(e, r.chat) } }
  async createInvite(r: W.TelegramCreateInviteRequest) { const x = await this.group(r.chat); const o = r.options; try { const invite = await this.client.createInviteLink(x.id, { expires: o.expireSeconds == null ? undefined : new Date(Date.now() + o.expireSeconds * 1000), usageLimit: o.usageLimit == null ? Infinity : o.usageLimit, withApproval: o.requestNeeded }); return { chat_id: x.group.id, invite: this.invite(invite) } } catch (e) { throwWriteError(e, r.chat) } }
  async editInvite(r: W.TelegramEditInviteRequest) { const x = await this.group(r.chat); const o = r.options; try { const invite = await this.client.editInviteLink({ chatId: x.id, link: r.link, expires: o.expireSeconds === undefined ? undefined : o.expireSeconds === null ? new Date(0) : new Date(Date.now() + o.expireSeconds * 1000), usageLimit: o.usageLimit === undefined ? undefined : o.usageLimit ?? Infinity, withApproval: o.requestNeeded }); return { chat_id: x.group.id, invite: this.invite(invite) } } catch (e) { throwWriteError(e, r.chat) } }
  async revokeInvite(r: W.TelegramRevokeInviteRequest) { const x = await this.group(r.chat); try { return { chat_id: x.group.id, invite: this.invite(await this.client.revokeInviteLink(x.id, r.link)) } } catch (e) { throwWriteError(e, r.chat) } }
  async listInviteMembers(r: W.TelegramListInviteMembersRequest) { const x = await this.group(r.chat); try { const rows = await this.client.getInviteLinkMembers(x.id, { link: r.link, limit: r.limit }); return { chat_id: x.group.id, link: r.link, members: rows.map(mapMember), total: validTotal(rows.total) } } catch (e) { throwWriteError(e, r.chat) } }
  approveJoinRequest(r: W.TelegramApproveJoinRequestRequest) { return this.mutate(r, 'approveJoinRequest', id => this.client.hideJoinRequest({ chatId: id, user: normalizePeerId(r.user), action: 'approve' })) }
  declineJoinRequest(r: W.TelegramDeclineJoinRequestRequest) { return this.mutate(r, 'declineJoinRequest', id => this.client.hideJoinRequest({ chatId: id, user: normalizePeerId(r.user), action: 'decline' })) }
  approveAllJoinRequests(r: W.TelegramApproveAllJoinRequestsRequest) { return this.mutate(r, 'approveAllJoinRequests', id => this.client.hideAllJoinRequests({ chatId: id, action: 'approve' })) }
  declineAllJoinRequests(r: W.TelegramDeclineAllJoinRequestsRequest) { return this.mutate(r, 'declineAllJoinRequests', id => this.client.hideAllJoinRequests({ chatId: id, action: 'decline' })) }
}
function validTotal(value: unknown) { return typeof value === 'number' && Number.isSafeInteger(value) && value >= 0 ? value : null }
function mapMember(m: ChatInviteLinkMember): W.TelegramGroupInviteMemberRecord { return { user_id: m.user.id, display_name: m.user.displayName, username: m.user.username ?? null, joined_at: m.date?.toISOString() ?? null, requested: m.isPendingRequest } }
